CREATE TABLE `cbc_social` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`class` INT(10) NULL DEFAULT NULL,
	`student` INT(10) NULL DEFAULT NULL,
	`term` INT(10) NULL DEFAULT NULL,
	`year` INT(10) NULL DEFAULT NULL,
	`cons` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`org` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`comm` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`accept` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ind` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`others` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`school` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`home` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`cs` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`rev` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`property` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`groupw` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`coop` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`time_` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`conf` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`conce` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`punctual` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`motivation` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`fluent` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`mtrr` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`speed` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`kasi` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`compr` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`klw` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`exte` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ziada` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`tone` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sauti` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`spell` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`hj` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`remarks` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`created_by` INT(10) NULL DEFAULT NULL,
	`modified_by` INT(10) NULL DEFAULT NULL,
	`created_on` INT(10) NULL DEFAULT NULL,
	`modified_on` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT;
