CREATE TABLE `assignment_list` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`assgn_id` INT(11) NULL DEFAULT NULL,
	`class` INT(11) NULL DEFAULT NULL,
	`created_by` INT(11) NULL DEFAULT NULL,
	`modified_by` INT(11) NULL DEFAULT NULL,
	`created_on` INT(11) NULL DEFAULT NULL,
	`modified_on` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4;
