CREATE TABLE `fee_pledge` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`student` INT(11) NULL DEFAULT NULL,
	`pledge_date` INT(11) NULL DEFAULT NULL,
	`amount` FLOAT NULL DEFAULT NULL,
	`status` VARCHAR(256) NOT NULL DEFAULT '',
	`remark` TEXT NULL,
	`created_by` INT(11) NULL DEFAULT NULL,
	`modified_by` INT(11) NULL DEFAULT NULL,
	`created_on` INT(11) NULL DEFAULT NULL,
	`modified_on` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT
AUTO_INCREMENT=3;
